amqp:
  admin:
    auto-create: false
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

my-sql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:3306


server:
  port: 8080
  undertow:
    threads:
      worker: 10 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One